version: '3'

dotenv: [".env"]

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  ollama:check:
    desc: Check if Ollama is running
    cmds:
      - |
        if [ "${OLLAMA_ENABLED}" = "false" ]; then
          echo "Ollama is disabled via OLLAMA_ENABLED=false. Skipping check."
        else
          curl -s http://localhost:11434 > /dev/null || (echo "Error: Ollama is not running. Please start Ollama." && exit 1)
        fi
    silent: true

  ollama:stop:
    desc: Stop Ollama service via Homebrew
    cmds:
      - brew services stop ollama

  ollama:start:
    desc: Start Ollama service via Homebrew
    cmds:
      - brew services start ollama

  ollama:restart:
    desc: Restart Ollama service via Homebrew
    cmds:
      - task: ollama:stop
      - task: ollama:start

  install:model:
    desc: Pull the required Ollama model
    deps: [ollama:check]
    cmds:
      - ollama pull mistral-nemo:latest

  install:
    desc: Install Python dependencies
    cmds:
      - source .venv/bin/activate && pip install -r requirements.txt

  run:
    desc: Run the Streamlit app locally
    cmds:
      - source .venv/bin/activate && streamlit run app.py

  test:
    desc: Run tests
    cmds:
      - source .venv/bin/activate && pylint **/*.py
      - source .venv/bin/activate && PYTHONPATH=. pytest -v ./tests

  docker:build:
    desc: Build the Docker container
    cmds:
      - docker-compose build

  docker:up:
    desc: Run the Docker container
    deps: [ollama:check]
    cmds:
      - docker-compose up

  docker:down:
    desc: Stop the Docker container
    cmds:
      - docker-compose down


  test-ci:
    desc: Run GitHub Actions locally using act (requires Docker)
    preconditions:
      - sh: command -v act >/dev/null 2>&1
        msg: "act is not installed. Install it with 'brew install act' or visit https://github.com/nektos/act"
    cmds:
      - act --validate
      - act --container-architecture linux/arm64 -P ubuntu-latest=catthehacker/ubuntu:act-latest
