version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  check-ollama:
    desc: Check if Ollama is running
    cmds:
      - 'curl -s http://localhost:11434 > /dev/null || (echo "Error: Ollama is not running. Please start Ollama." && exit 1)'
    silent: true

  stop-ollama:
    desc: Stop Ollama service via Homebrew
    cmds:
      - brew services stop ollama

  start-ollama:
    desc: Start Ollama service via Homebrew
    cmds:
      - brew services start ollama

  restart-ollama:
    desc: Restart Ollama service via Homebrew
    cmds:
      - task: stop-ollama
      - task: start-ollama

  install:
    desc: Install Python dependencies
    cmds:
      - source .venv/bin/activate && pip install -r requirements.txt

  run:
    desc: Run the Streamlit app locally
    deps: [check-ollama]
    cmds:
      - source .venv/bin/activate && streamlit run app.py

  test:
    desc: Run tests
    cmds:
      - source .venv/bin/activate && pytest -v ./tests

  docker:build:
    desc: Build the Docker container
    cmds:
      - docker-compose build

  docker:up:
    desc: Run the Docker container
    deps: [check-ollama]
    cmds:
      - docker-compose up

  docker:down:
    desc: Stop the Docker container
    cmds:
      - docker-compose down
